version: '3.8'

services:
  backend:
    build: .
    container_name: fastsock_backend
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app/static:/app/app/static
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fastsock
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-changethis_secret_key_for_jwt_encoding_decoding_12345}
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: fastsock_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: fastsock_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastsock
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:latest
    container_name: fastsock_redis
    restart: always

volumes:
  postgres_data:
